apiVersion: ipam.nephio.org/v1alpha1
kind: IPAllocation
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
  creationTimestamp: null
  labels:
    nephio.org/interface: internet
  name: upf-avicha-edge-1-internet
  namespace: upf8s
spec:
  kind: pool
  prefixLength: 16
  selector:
    matchLabels:
      nephio.org/network-instance: sample-vpc
status: {}
