apiVersion: ipam.nephio.org/v1alpha1
kind: IPAllocation
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
  creationTimestamp: null
  labels:
    nephio.org/interface: n3
  name: upf-avicha-edge-1-n3
  namespace: upf8s
spec:
  kind: network
  selector:
    matchLabels:
      nephio.org/network-instance: sample-vpc
      nephio.org/network-name: sample-n3-net
status: {conditionedstatus: {conditions: []}, allocatedprefix: 100.0.0.3/32, gateway: 100.0.0.1}
